name: Android Feature Branch CI

on:
  push:
    branches:
      - '*/*'

jobs:
  auto-pull-request:
    name: Open pull request after push
    runs-on: ubuntu-latest

    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}