name: Open pull request after push

on:
  push:
    branches:
      - '*/*'

jobs:
  open-pull-request:
    name: Open the pull request
    runs-on: ubuntu-latest

    steps:
      - name: open-pull-request-action
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_ASSIGNEES: "ALefaux"
