name: Valid pull request after open it

on:
  pull_request

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}