name: Add label on pull request after review submitted

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    name: Auto merge the pull request
    runs-on: ubuntu-latest

    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@7ab42e888a333bf77ce865bc84fedc6a365a3548"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"