name: Merge pull request after review submitted

on:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  automerge:
    name: Auto merge the pull request
    runs-on: ubuntu-latest

    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "automerge"